include/emitc/Dialect/EmitC/EmitC.td
Takes over the upstream changes llvm/llvm-project@89eab30 to EmitC.
=> Use OpBuilderDAG instead of OpBuilder

docs/mhlo-op-coverage.md, include/emitc/Dialect/EmitC/Passes.h, include/emitc/Dialect/EmitC/Passes.td, include/emitc/emitc_mhlo.h, include/emitc/emitc_tensor.h, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Conversion/mhlo-to-emitc.mlir, unittests/emitc_mhlo.cpp, unittests/emitc_tensor.cpp
See #6 for progress on other model architectures.
=> Support MobileNet/MobileNetV2 inference

docs/mhlo-op-coverage.md, include/emitc/emitc_mhlo.h, include/emitc/emitc_tensor.h, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, test/Conversion/mhlo-to-emitc.mlir, unittests/emitc_mhlo.cpp
=> Add ReduceWindowOp

include/emitc/Conversion/Passes.h, include/emitc/Conversion/Passes.td, include/emitc/Dialect/EmitC/Passes.h, include/emitc/Dialect/EmitC/Passes.td, include/emitc/InitPasses.h, lib/Conversion/MHLOToStd.cpp, lib/Conversion/PassDetail.h, lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/PassDetail.h, lib/Dialect/EmitC/Conversion/SCFToEmitC.cpp, lib/Dialect/EmitC/Conversion/StdToEmitC.cpp
* Move pass registration
* Use base classes generated by tablegen for conversion passes
=> Refactor passes

README.md
=> Fix reference to mlir build script

.github/workflows/build-and-test.yaml, scripts/generate_testscases.py, scripts/get_mobilenet_v2.py, scripts/keras_to_savedmodel.py, scripts/optimize_tf_dialect.py, scripts/requirements.txt, scripts/savedmodel_to_tf_dialect.py, scripts/tf_to_mhlo_dialect.py
This finally publishes and utilized our internal script to generate and run an e2e test as part of our GitHub action.
=> Add an e2e test to our pipeline

docs/mhlo-op-coverage.md, include/emitc/emitc_mhlo.h, unittests/emitc_mhlo.cpp
=> Implement SliceOp for Tensor3D and Tensor4D

include/emitc/emitc_mhlo.h, unittests/emitc_mhlo.cpp
* Handle the case, when broadcasting dimensions of size 1
* Add testcases
Co-authored-by: David Ronnenberg <david.ronnenberg@iml.fraunhofer.de>
=> Fix broadcast_in_dim operation

lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp
=> Remove unused variable

include/emitc/Target/Cpp.h, lib/Target/Cpp/TranslateToCpp.cpp
Add a new helper method which emits the type and a new variable name for an OpResult.
=> Add emitVariableDeclaration method

docs/EmitC.md, include/emitc/Dialect/EmitC/CMakeLists.txt, include/emitc/Dialect/EmitC/EmitC.td, include/emitc/Dialect/EmitC/EmitCDialect.h, lib/Dialect/EmitC/CMakeLists.txt, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/IR/EmitCDialect.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Conversion/mhlo-to-emitc.mlir, test/Target/common-cpp.mlir, test/Target/const.mlir
=> Implement an emitc opaque attribute

lib/Target/Cpp/TranslateToCpp.cpp
=> Drop printConstantOp template

include/emitc/Dialect/EmitC/IR/CMakeLists.txt, include/emitc/Dialect/EmitC/IR/EmitC.h, include/emitc/Dialect/EmitC/IR/EmitC.td, include/emitc/Dialect/EmitC/IR/EmitCAttrDefs.td, include/emitc/Dialect/EmitC/IR/EmitCBase.td, include/emitc/Dialect/EmitC/IR/EmitCTypes.td, include/emitc/Target/Cpp/Cpp.h, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, lib/Dialect/EmitC/IR/EmitC.cpp, lib/Target/Cpp/TranslateRegistration.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Conversion/mhlo-to-emitc.mlir, test/Conversion/tosa-to-emitc.mlir, test/Dialect/EmitC/invalid_ops.mlir, test/Dialect/EmitC/ops.mlir, test/Target/common-cpp.mlir, test/Target/const.mlir, test/Target/invalid-c.mlir
Address (most) review comments of https://reviews.llvm.org/D103969.
Updating the code in our repo before updating (and splitting) the patch under review.
=> Address review comments

include/emitc/Dialect/EmitC/IR/EmitC.td, include/emitc/Dialect/EmitC/IR/EmitCAttributes.td, include/emitc/Dialect/EmitC/IR/EmitCTypes.td, lib/Dialect/EmitC/IR/EmitC.cpp, test/Dialect/EmitC/invalid_ops.mlir, test/Dialect/EmitC/ops.mlir, test/Dialect/EmitC/types.mlir
..for the dialect itself :partying_face:
=> Address review comments - final round..

lib/Target/Cpp/TranslateToCpp.cpp
Mainly ..
* Replaces auto placeholders by explicit types
* Drops namespace qualifiers
* Revises comments
=> Cleanup Cpp target

lib/Target/Cpp/TranslateToCpp.cpp
Uses overloading to select the appropriate `printOperation()`. Also
drops our former implementation of `printOperation()`, whose logic is
moved into `emitOperation()`.
=> Use TypeSwitch to differentiate between ops

lib/Target/Cpp/TranslateToCpp.cpp
Error messages are sentence fragments that should start with lower case
and that shouldn't end with punctuation.
=> Fix error messages

lib/Target/Cpp/TranslateToCpp.cpp
Passes the location instead of the op, if the the op was only passed to
emit an error.
=> Pass location instead of op

lib/Target/Cpp/TranslateToCpp.cpp
Replaces `shouldMapToSigned` by `shouldMapToUnsigned` as proposed in
https://reviews.llvm.org/D104632#2960311.
=> Replace shouldMapToSigned by shouldMapToUnsigned

reference-implementation/unittests/tosa.cpp
=> Refactor tosa unittests

scripts/e2e_test.sh, scripts/e2e_test_tosa.sh, scripts/optimize_tf_dialect.py, scripts/requirements.txt, scripts/tf_to_mhlo_dialect.py, scripts/tf_to_tosa_dialect.py
Further fixes and updates the e2e scripts.
=> Upgrade to tf-nightly==2.9.0.dev20220401

include/emitc/Dialect/EmitC/Conversion/Passes.h, include/emitc/Dialect/EmitC/Transforms/Passes.h, lib/Dialect/EmitC/Conversion/ArithToEmitC.cpp, lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/TensorToEmitC.cpp, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, lib/Dialect/EmitC/Transforms/InsertIncludes.cpp
Prepares for an upstream change that drops some includes.
=> Refactor includes

lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, reference-implementation/include/emitc/core_ops.h
Updates MLIR-HLO usage to match tensorflow/mlir-hlo@d5aa9ce.
=> Integrate MHLO at tensorflow/mlir-hlo@d5aa9ce

reference-implementation/unittests/tosa.cpp
Eliminates warnings previously reported with `-Wbraced-scalar-init`.
=> Fix build warnings

reference-implementation/unittests/tosa.cpp
=>  Reenable `tosa.rescale` test
