include/emitc/Target/Cpp.h, lib/Target/Cpp/TranslateToCpp.cpp
Makes the CppEmitter public to allow reusage in custom translators (e.g.
we use it in IREE's VM C target). Further, makes the interleave functions
public. Changes were originaly introduced on branch `iree` by Simon.
This ports these changes from `iree` to `main`.
=> Make functions public to allow reusage

tools/emitc-opt/CMakeLists.txt
The CMake targets MLIR{GPU,Linalg,Standard}ToSPIRVTransforms were
renamed to MLIR{GPU,Linalg,Standard}TOSPIRV.
=> Fix MLIR*ToSPIRVTransforms target naming

lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp, lib/Target/Cpp/TranslateToCpp.cpp
'getParentOp' and 'getParentOfType' are deprecated. Use
Operation::getParentOp() and Operation::getParentOfType() instead.
=> Refactor use of getParentOp and getParentOfType

include/emitc/emitc_types.h
So far, gcc moaned that e.g. `struct std::array<long unsigned int, 1>` has no
user-provided default constructor and the implicitly-defined
constructor does not initialize
`long unsigned int std::array<long unsigned int, 1>::_M_elems [1]`.
Co-authored-by: David Ronnenberg <david.ronnenberg@iml.fraunhofer.de>
=> Fix gcc warnings

include/emitc/emitc_types.h
Reduces the size for MobileNetv2 from `15778496` to `15769032` byte.
=> Pass data to unary/binary templated function as const reference

include/emitc/emitc_types.h, unittests/emitc_mhlo.cpp, unittests/emitc_types.cpp
Add template specifications (Tensor3D and Tensor4D ) for the function concat. Also add some unittests for it.
Closes #43
=> Extend mhlo::concatenate and concat for 3D and 4D tensors

.github/workflows/build-and-test.yaml, scripts/e2e_test.sh, scripts/generate_testscases.py, scripts/model_to_savedmodel_with_predict_function.py
The existing test pipeline already worked with both keras and tensorflow saved models, hence I generalized the naming and the content of the scripts. Since I renamed the script, I also updated the github build-and-test.yaml. 
Furthermore the test case generator can now handle int32 as output type of operations.
=> Generalize e2e pipeline test to work with keras and tensorflow saved models

include/emitc/emitc_mhlo.h, lib/Target/Cpp/TranslateToCpp.cpp, test/Conversion/mhlo-to-std.mlir, test/Conversion/std-to-emitc.mlir, test/Conversion/tensor-to-emitc.mlir, test/Target/cpp-calls.mlir
These were leftovers from the move to a variadic template for the Tensor type.
=> Remove dimension specific typedefs

CMakeLists.txt
The upstream CMake minimum was bumped with llvm/llvm-project@afa1afd.
This allows to remove dead code setting policies to NEW, see the
upstream commit llvm/llvm-project@480643a.
=> Bump CMake minimum to 3.13.4 and remove dead code

include/emitc/emitc_core_ops.h, include/emitc/emitc_mhlo.h
This introduces are core ops header in which common ops are implemented.
Those common ops can be called/used from different conversion passes.
=> Introduce core ops header and move mhlo::abs to it

docs/tosa-op-coverage.md, include/emitc/emitc_core_ops.h, include/emitc/emitc_mhlo.h, include/emitc/emitc_tosa.h, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir
Adds `add` and `exp` operations to `emitc_tosa.h` and corresponding tests. To achieve a shared implementation between mhlo and tosa these ops were moved from `emitc_mhlo.h` to `emitc_core_ops.h`.
=> Add TOSA add and exp operations

docs/tosa-op-coverage.md, include/emitc/emitc_core_ops.h, include/emitc/emitc_mhlo.h, include/emitc/emitc_tosa.h, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir, unittests/CMakeLists.txt, unittests/emitc_tosa.cpp
This adds conversions for `tosa.reciprocal` and `tosa.rsqrt`. Also adds tests for conversions and functions. `tosa.rsqrt` is splitted into two `emitc::CallOp`: `emitc::sqrt` and `tosa::reciprocal`.
=> Add conversions for tosa.reciprocal and tosa.rsqrt.

lib/Dialect/EmitC/IR/EmitCDialect.cpp
'getAttrs' has been explicitly marked deprecated. This patch refactors
to use Operation::getAttrs().
=> Replace deprecated 'getAttrs'

docs/EmitC.md, include/emitc/Dialect/EmitC/EmitC.td, lib/Dialect/EmitC/IR/EmitCDialect.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Dialect/EmitC/ops.mlir, test/Target/cpp-calls.mlir
Our constant operation is intended to support opaque attributes as well
as our opaque type.
=> Implement basic ConstOp

docs/tosa-op-coverage.md, include/emitc/emitc_core_ops.h, include/emitc/emitc_mhlo.h, include/emitc/emitc_tosa.h, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir, unittests/emitc_tosa.cpp
This will also move the mhlo.dot op implementation to the emitc core ops, since we can reuse the implementation for the tosa.matmul op.
=> Add conversion for tosa.matmul

docs/tosa-op-coverage.md, include/emitc/emitc_mhlo.h, include/emitc/emitc_tosa.h, unittests/emitc_mhlo.cpp, unittests/emitc_tosa.cpp
This verifies that the TOSA and MHLO convolution implementation support strided convolutions by adding unittests.
=> Add unittests for strided Conv2d

README.md, include/emitc/InitTranslation.h, include/emitc/Target/Cpp.h, lib/Target/CMakeLists.txt, lib/Target/Cpp/TranslateToCRegistration.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Target/c-calls.mlir
The C target is a special form of C++ target, which supports emitting C
code for a limited subset of operations and types. For example the C
target does not support tensors or multiple return values. Furthermore,
assignments use = and never the curly-brace-delimited initializer which
is used in the C++ target.
=> Create initial C target

lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir
This changes the type of the attributes of the converted `tosa::conv2d` op to dense. This is mandatory for `emitc-translate --mlir-to-cpp`.
=> Change tosa::conv2d attributes type to dense

include/emitc/Target/Cpp.h, lib/Target/Cpp/TranslateToCpp.cpp
Introduces a flag to enforce the the printer to forward declare all
emitted variables.
=> Introduce the `forwardDeclareVariables` flag

include/emitc/emitc_core_ops.h, include/emitc/emitc_mhlo.h, include/emitc/emitc_tosa.h, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir, unittests/emitc_tosa.cpp
This also moves the mhlo.clamp op implementation to the emitc core ops, so that we can reuse the implementation for tosa.reluN.
=> Add conversion for tosa.reluN

docs/tosa-op-coverage.md, include/emitc/emitc_tosa.h, include/emitc/emitc_types.h, include/emitc/emitc_utility.h, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir, unittests/emitc_tosa.cpp, unittests/emitc_types.cpp
Adds a conversion for `tosa.depthwise_conv2d`, the corresponding unittest and regression test. Also adds utility functions to calculate the index to a flat array for a given shape and indices (ravel index). This is needed in the `depthwise_conv2d` implementation.
=> Add conversion for tosa.depthwise_conv2d 

include/emitc/emitc_core_ops.h, include/emitc/emitc_tosa.h, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir
Fixes the case, where the bit width of the operand does not match the one from the max attributes.
=> Fix tosa.reluN conversion

lib/Target/Cpp/TranslateToCpp.cpp
This include makes the `size_t` available in C.
=> Add missing import for C Target

.github/workflows/build-and-test.yaml
Adds a first TOSA e2e test to our pipeline and splits the workflow to build and test the release and debug build in parallel.
=> Add a TOSA e2e test to our pipeline

lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/tosa-to-emitc.mlir
This cleans up the IR by not emitting empty template args.
=> Don't emit empty template arguments

scripts/tf_to_mhlo_dialect.py
Referring to the MLIR glossary, this is a conversion and not a
translation.
=> Rename translate() to convert()

test/Conversion/mhlo-to-emitc.mlir, test/Conversion/std-to-emitc.mlir, test/Conversion/tensor-to-emitc.mlir
We now explicitly check that were piped to emitc-translate before and not checked separately. Furthermore, the MHLO to EmitC tests are expanded (check inputs and outputs as well as arguments and template arguments). The latter also revealed that some non empty template arguments were not checked before.
=> Expand and refactor tests

include/emitc/Dialect/EmitC/EmitC.td, lib/Dialect/EmitC/IR/EmitCDialect.cpp, test/Dialect/EmitC/invalid_ops.mlir
This adds the following checks to the `emitC::CallOp` verifier:
- args: arguments need a type
- template_args: arguments need a type, forbid float literals, forbid dense elements attributes
=> Add more checks to emitc::CallOp verifier

.github/workflows/build-and-test.yaml, scripts/e2e_test.sh, scripts/e2e_test_tosa.sh
Makes sure to remove if trailing commas are present after stripping
`tf._input_shapes` from the attributes (it might be that it was the last
attribute).
=> Remove trailing comma from attributes

test/Dialect/EmitC/ops.mlir
Till now this was only covered in Target/common-cpp.mlir and was thus
never parsed by emitc-opt.
=> Add emitc.getaddressof op to EmitC ops tests

include/emitc/Dialect/EmitC/CMakeLists.txt
The `add_mlir_doc` CMake macro has changed upstream with commit
llvm/llvm-project@90ae4d90.
=> Reorder arguments passed to `add_mlir_doc`

docs/EmitC.md, include/emitc/Dialect/EmitC/EmitC.td, lib/Dialect/EmitC/IR/EmitCDialect.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Dialect/EmitC/invalid_ops.mlir, test/Dialect/EmitC/ops.mlir, test/Target/common-cpp.mlir
This replaces the `emitc.getaddressof` op in favor of the newly added
`emitc.apply`. The `emitc.apply` op allows to specify the operator to
apply (the applicable operator). This not only allows a "get address"
using the & operator, as it also enables a "get content" via the *
operator.
=> Drop GetAddressOfOp in favor of ApplyOp

include/emitc/emitc_mhlo.h, include/emitc/emitc_std.h, include/emitc/emitc_tensor.h, include/emitc/emitc_tosa.h, lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/StdToEmitC.cpp, lib/Dialect/EmitC/Conversion/TensorToEmitC.cpp, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, test/Conversion/mhlo-to-emitc.mlir, test/Conversion/std-to-emitc.mlir, test/Conversion/tensor-to-emitc.mlir, test/Conversion/tosa-to-emitc.mlir, test/MobileNetV2_tosa_test.cpp, unittests/emitc_mhlo.cpp, unittests/emitc_std.cpp, unittests/emitc_tensor.cpp, unittests/emitc_tosa.cpp
All our header only functions are actually reference implementations provided within the scope of `emitc`. Therefore, this moves the `mhlo`, `standard`, `tensor` and `tosa` namespaces into the top-level `emitc` namespace. The `emitc` namespace used in MIR-related parts will soon be moved to `mlir::emitc`.
=> Move dialect specific namespaces into `emitc`

docs/EmitC.md, include/emitc/Dialect/EmitC/EmitC.td, include/emitc/Dialect/EmitC/EmitCDialect.h, lib/Target/Cpp/TranslateToCpp.cpp, test/Dialect/EmitC/ops.mlir, test/Target/common-cpp.mlir
This adds an include operation that allows to  define a source file
inclusion via `#include` directive. With the unit attribute
`is_standard_include` defined, the inclusion is emitted as
`#include <filename>`. Otherwise the inclusion is emitted as
`#include "filename"`.
=> Add EmitC include operation

include/emitc/Dialect/EmitC/Conversion/CMakeLists.txt, lib/Dialect/EmitC/Conversion/CMakeLists.txt, tools/emitc-opt/CMakeLists.txt
Renames the CMake target MLIREmitCPassIncGen to
MLIREmitCConversionPassIncGen. The former name will be used
Transform passes.
=> Rename CMake target MLIREmitCPassIncGen

include/emitc/Dialect/EmitC/Conversion/Passes.td, include/emitc/Target/Cpp/TranslationFlags.h, lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/StdToEmitC.cpp, lib/Dialect/EmitC/Conversion/TensorToEmitC.cpp, lib/Target/Cpp/TranslationFlags.cpp
Revises the license headers of our sources files. With this we
distinguish between files that will be upstreamed and those files that
will (for now!) remain in the mlir-emitc repository.
=> Revise license headers

lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/StdToEmitC.cpp, lib/Dialect/EmitC/Conversion/TensorToEmitC.cpp, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp
Renames OwningRewritePatternList to RewritePatternSet, as with upstream
commit llvm/llvm-project@dc4e913b. Also renames `patterns.insert` to
`patterns.add`.
=> Mechaincal Change: Rename OwningRewritePatternList

include/emitc/Target/Cpp/CppEmitter.h, lib/Target/Cpp/TranslateToCpp.cpp
For the use of braces in if/else/loop-statements, see the [LLVM Coding Standards](https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements).
=> Address review comments

include/emitc/Target/Cpp/CppEmitter.h, lib/Target/Cpp/TranslateRegistration.cpp, lib/Target/Cpp/TranslateToCpp.cpp, test/Target/Cpp/call-cpp.mlir, test/Target/Cpp/call.mlir, test/Target/Cpp/const.mlir, test/Target/Cpp/control_flow.mlir, test/Target/Cpp/for.mlir, test/Target/Cpp/if.mlir, test/Target/Cpp/invalid.mlir, test/Target/Cpp/stdops-cpp.mlir, test/Target/Cpp/stdops.mlir
Renames `forwardDeclareVariables` to `declareVariablesAtTop`. Further
updates comments and refactors early returns.
=> Rename and refactor `forwardDeclareVariables`

include/emitc/Target/Cpp/CppEmitter.h
The definition of the function was already removed from our codebase.
=> Tidy up leftover

include/emitc/Target/Cpp/CppEmitter.h, lib/Target/Cpp/TranslateRegistration.cpp, lib/Target/Cpp/TranslateToCpp.cpp
There is no need to expose/pass through `trailingSemicolon` via
`translateToCpp()`.
=> Don't expose `trailingSemicolon` via translation

build_tools/llvm_version.txt
Updates LLVM usage to match llvm/llvm-project@b36c4bb3.
Further updates the MLIR-HLO submodule to tensorflow/mlir-hlo@b67f34aa.
=> Integrate LLVM at llvm/llvm-project@b36c4bb3

CMakeLists.txt, tools/emitc-opt/CMakeLists.txt, tools/emitc-opt/emitc-opt.cpp, tools/emitc-translate/CMakeLists.txt
IREE does no longer depend on mlir-emitc as a submodule.
=> Remove IREE build options

tools/emitc-opt/CMakeLists.txt, tools/emitc-opt/emitc-opt.cpp
We only use the `mhlo-control-flow-to-scf` conversion pass from the
tensorflow/mlir-hlo repo. This drops all other mhlo passes.
=> Drop mhlo passes

test/testCorrectGroundTruthWithHMC_canon_inline.mlir, tools/emitc-opt/emitc-opt.cpp
The `mhlo-control-flow-to-scf` is broken and dropped upstream with
commit tensorflow/mlir-hlo@/f5296af. With this commit we switch over to
use the `mhlo-legalize-control-flow` pass, similar to what IREE does.
=> Replace `mhlo-control-flow-to-scf`

.github/workflows/build-and-test.yaml, README.md, unittests/CMakeLists.txt
In preparation to move the EmitC header-only reference implementation
to its own CMake project, unit tests are now build with pure CMake.
=> Build unit tests without `add_mlir_unittest`

unittests/emitc_tosa_eigen.cpp
If `EMITC_TOSA_USE_EIGEN` is defined is already checked in the
`emitc_tosa.h` itself, which then includes `emitc_tosa_eigen.h`.
=> Always include `emitc_tosa.h`

.github/workflows/build-and-test.yaml, CMakeLists.txt, include/emitc/CMakeLists.txt
Allows to set building and testing with Eigen separately.
=> Introduce EMITC_TOSA_USE_EIGEN build option

include/emitc/Dialect/EmitC/Conversion/Passes.h, include/emitc/Dialect/EmitC/Conversion/Passes.td, lib/Dialect/EmitC/Conversion/ArithToEmitC.cpp, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, lib/Dialect/EmitC/Conversion/StdToEmitC.cpp, lib/Dialect/EmitC/Conversion/TensorToEmitC.cpp, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp
Replaces the deprecated FunctionPass in favor of OperationPass<FuncOp>.
This is changed upstream with commit llvm/llvm-project@4157455.
=> Replace deprecated FunctionPass

lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, reference-implementation/include/emitc/mhlo.h, test/Conversion/mhlo-to-emitc.mlir
Drops the conversion and reference implementation for the
`mhlo.rng_bit_generator` op. The op is modified by upstream with commit
tensorflow/mlir-hlo@80ebc34 and was not properly supported within our
reference implementation anyway.
=> Drop support for `mhlo.rng_bit_generator`

lib/Dialect/EmitC/Conversion/MHLORegionOpsToEmitC.cpp
The "convert-mhlo-region-ops-to-emitc" pass inserts a `std.return`
(::mlir::ReturnOp) but did not depend on the StandardOps dialect.
=> Add missing dependent dialect

reference-implementation/include/emitc/mhlo.h, reference-implementation/unittests/mhlo.cpp, test/Conversion/mhlo-to-emitc.mlir
According to
https://www.tensorflow.org/mlir/hlo_ops#mhloselect_mlirmhloselectop the
tensor of pred may be a scalar in which case it is broadcasted. Instead
of broadcasting we keep it a 0D tensor and overload the reference
implementation with a function that handles it accordingly.
Fixes #280
=> Expand `mhlo::select` and refactor unit tests

test/Conversion/arith-to-emitc.mlir, test/Conversion/mhlo-to-emitc.mlir, test/Conversion/tensor-to-emitc.mlir, test/Conversion/tosa-to-emitc.mlir, test/MobileNetV2_FakeWeights_mhlo.mlir, test/MobileNetV2_FakeWeights_tosa.mlir
The special case parsing of func will be removed upstream.
=> Replace textual references of func by func.func

docs/tosa-op-coverage.md, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, reference-implementation/include/emitc/tosa.h, reference-implementation/unittests/tosa.cpp, test/Conversion/tosa-to-emitc.mlir
=> Add support for tosa argmax operation

scripts/requirements.txt
The pipeline fails with newer protobuf versions:
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
=> Pin protobuf to version 3.20.1

CMakeLists.txt
Enables building as an in-tree build as an LLVM external project.
This requires to set `LLVM_EXTERNAL_PROJECTS="mlir-emitc"` and to pass
the source dir of mlir-emitc via `LLVM_EXTERNAL_MLIR_EMITC_SOURCE_DIR`.
=> Enable in-tree builds with LLVM_EXTERNAL_PROJECTS

CMakeLists.txt, test/lit.site.cfg.py.in
Fixes running the lit tests if building as an in-tree-build via the
`LLVM_EXTERNAL_PROJECTS` mechanism.
=> Fix running lit tests

docs/mhlo-op-coverage.md, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp, test/Conversion/mhlo-to-emitc.mlir
Updates MLIR-HLO usage to match tensorflow/mlir-hlo@1e2ff39.
=> Integrate MHLO at tensorflow/mlir-hlo@1e2ff39

scripts/requirements.txt
A fresh install of tf-nightly==2.10.0.dev20220519 fails with:
`
ERROR: tb-nightly 2.10.0a20220712 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.20.0 which is incompatible.
`
=> Pin protobuf to version 3.19.4

build_tools/llvm_version.txt, lib/Dialect/EmitC/Conversion/MHLOToEmitC.cpp
Updates LLVM usage to match llvm/llvm-project@131dda9.
Further updates the MLIR-HLO submodule to tensorflow/mlir-hlo@817776b.
=> Integrate LLVM at llvm/llvm-project@131dda9

CMakeLists.txt
The variable is now set a cache variable by upstream.
=> Don't explicitly set MLIR_TABLEGEN_EXE

docs/tosa-op-coverage.md, lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp, reference-implementation/include/emitc/tosa.h, reference-implementation/unittests/tosa.cpp, test/Conversion/tosa-to-emitc.mlir
The ReluN operator was removed from the TOSA spec and the MLIR op is
removed with llvm/llvm-project@9dec80b. This patch therefore drops the
conversion to EmitC as well as the reference implementation. The latter
already relied on clamp. Hence, tests are moved instead of dropped.
=> Remove ReluN conversion and implementation

.github/workflows/build-and-test.yaml, .github/workflows/lint.yaml
This updates the used actions to newer versions and specifies a specific
commit instead of a tag or a branch, which can be overwritten by a
maintainer of the action.
=> Update actions and pin to commit

lib/Conversion/TosaToEmitC/TosaToEmitC.cpp
Nearly duplicates `getI64ElementsAttr`, but that should be okay for now.
=> Implement `getI32ElementsAttr` helper function

docs/tosa-op-coverage.md, lib/Conversion/TosaToEmitC/TosaToEmitC.cpp, reference-implementation/include/emitc/core_ops.h, reference-implementation/include/emitc/mhlo.h, reference-implementation/include/emitc/tosa.h, reference-implementation/include/emitc/types.h, reference-implementation/unittests/tosa.cpp, test/Conversion/tosa-to-emitc.mlir
* As MHLO already had an implementation for concatenate and the inputs/outputs are identical, moved the existing MHLO concatenate implementation into core_ops and referenced it from both. 
* The createBroadcastOpIfNeeded was initially implemented to support binary ops only. However, very small changes were required to enable it in supporting broadcasting for more than two inputs. This can be further expanded by allowing callOpBroadcastableConversion to take in more than two inputs, but it may require more substantial changes that might not be worth it for (what is currently) a single op.
=> Implement tosa lowerings for gather, select and concat ops.

include/emitc/Conversion/Passes.h, include/emitc/Conversion/Passes.td, include/emitc/Conversion/StablehloToEmitC/StablehloToEmitC.h, include/emitc/InitPasses.h, lib/Conversion/CMakeLists.txt, lib/Conversion/StablehloToEmitC/CMakeLists.txt, lib/Conversion/StablehloToEmitC/StablehloToEmitC.cpp, test/Conversion/stablehlo-to-emitc.mlir, tools/emitc-opt/CMakeLists.txt, tools/emitc-opt/emitc-opt.cpp
This adds an initianl StableHLO to EmitC pass. The pass is compiled if the option `EMITC_ENABLE_HLO` is set. For now, StableHLO ops converted to C++ rely on the reference implementation for MHLO ops. This will change in the future. When adding more ops, docs will be added and code might be moved from the MHLO conversions to the StableHLO conversions to avoid code duplication. If suitable, the MHLO conversions will be replaced by the StableHLO ones.
=> Implement an initial StableHLO to EmitC pass

include/emitc/Conversion/EmitCCommon/GenericOpConversion.h, lib/Conversion/MhloToEmitC/MHLOToEmitC.cpp, lib/Conversion/StablehloToEmitC/StablehloToEmitC.cpp, lib/Conversion/TosaToEmitC/TosaToEmitC.cpp
Further renames `CallOpConversion` to `GenericOpConversion`.
=> Deduplicate `CallOpConversion`

reference-implementation/include/emitc/arith.h, reference-implementation/include/emitc/core_ops.h, reference-implementation/include/emitc/mhlo.h, reference-implementation/include/emitc/tensor.h, reference-implementation/include/emitc/tosa.h, reference-implementation/include/emitc/tosa_eigen.h, reference-implementation/include/emitc/types.h, reference-implementation/include/emitc/utility.h, reference-implementation/unittests/arith.cpp, reference-implementation/unittests/mhlo.cpp, reference-implementation/unittests/tensor.cpp, reference-implementation/unittests/tosa.cpp, reference-implementation/unittests/tosa_eigen.cpp, reference-implementation/unittests/types.cpp
Add copyright notices to the reference implementation for the case of
re-licensing.
As part of https://reviews.llvm.org/D146483, part of the reference
implementation is forked. Even if not as part of this pull request, it
might be of interest to change the license from `Apache-2.0` to
`Apache-2.0 WITH LLVM-exception`. The copyright notices can help to
facilitate this.
=> Add Copyright Notices

reference-implementation/include/emitc/arith.h, reference-implementation/include/emitc/core_ops.h, reference-implementation/include/emitc/stablehlo.h, reference-implementation/include/emitc/tensor.h, reference-implementation/include/emitc/tosa.h, reference-implementation/include/emitc/tosa_eigen.h, reference-implementation/include/emitc/types.h, reference-implementation/include/emitc/utility.h, reference-implementation/unittests/arith.cpp, reference-implementation/unittests/stablehlo.cpp, reference-implementation/unittests/tensor.cpp, reference-implementation/unittests/tosa.cpp, reference-implementation/unittests/tosa_eigen.cpp, reference-implementation/unittests/types.cpp
To facilitate an easy movement between MLIR-EmitC and upstream LLVM and MLIR, respectively, we are relicensing the reference implementation under Apache-2.0 WITH LLVM Exceptions.
=> Relicense under Apache-2.0 WITH LLVM Exceptions

reference-implementation/include/emitc/types.h, reference-implementation/unittests/types.cpp
This is used in the MGLO LLVM integration of emitc'ed models. Our infrastructure internally uses T* buffers to communicate between LLVM and the model (this was used to abstract away the details of TF/TFLite runtime vs interacting with a model in a python host vs EmitC) and so we need to be able to extract the underlying buffer of a EmitC Tensor.
This places a (light) data layout restriction on the Tensor implementation, as we need it to be in a columnar layout. This is already what the implementation did, so there is nothing too surprising here. I have added a unit test to enforce this restriction on the underlying buffer layout.
=> Add .get() method to Tensor<...>.

CMakeLists.txt
Upstream bumped the minimum version to 3.20.0.
=> Set minimum CMake version to 3.20.0

lib/Conversion/StablehloToEmitC/StablehloRegionOpsToEmitC.cpp, lib/Conversion/StablehloToEmitC/StablehloToEmitC.cpp, lib/Conversion/TosaToEmitC/TosaToEmitC.cpp
Replaces `{i,getI}64ElementsAttr` with `getI64TensorAttr`.
Closes #402
=> Replace `{i,getI}64ElementsAttr`

reference-implementation/include/emitc/tosa.h, reference-implementation/unittests/tosa.cpp
=> Refactor type of shift argument passed to tosa.rescale

.github/workflows/build-and-test.yaml
At these stages, it is sufficient to just check if a cache entry exists without downloading the cache.
=> Skip downloading caches

lib/Conversion/StablehloToEmitC/StablehloRegionOpsToEmitC.cpp, lib/Conversion/TensorToEmitC/TensorToEmitC.cpp, lib/Conversion/TosaToEmitC/TosaToEmitC.cpp
Switches member calls to `isa/dyn_cast/cast` to free function calls since calling member variants is deprecated, see
https://mlir.llvm.org/deprecation/.
=> Replace member calls with free function calls
